### ISSUE TITLE
Не работает автоматическое переключение статуса master

### ISSUE THREAD

**Issue by vitalyzhakov** [antonvash/redis-cluster#2]
```
git clone XXX
make init
```
Дожидаемся старта, проверяем в http://localhost:9000/haproxy_stats появление master.

Останавливаем master
```
docker stop redis-cluster_redis1_1
```

Ожидаемое поведение - срабатывает failover, статус master переходит на живую ноду кластера.

Фактическое поведение
![Снимок экрана от 2020-09-23 13-53-41](https://user-images.githubusercontent.com/1775220/93990335-6fc70800-fda4-11ea-9938-582a777cf680.png)

**Comment by antonvash** [comment]
там таймауты в композ файле у сентинеля. порядка минуты переключение происходит. 
REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS и REDIS_SENTINEL_FAILOVER_TIMEOUT. если выставить их в 5000 например то быстрее будет
![image](https://user-images.githubusercontent.com/25710668/93990806-a26d0280-fd9c-11ea-89a1-0a32c7f71aef.png)
![image](https://user-images.githubusercontent.com/25710668/93991184-0bed1100-fd9d-11ea-98ca-2cab2a198913.png)

**Comment by vitalyzhakov** [comment]
Покажите вывод команды `make init`?

**Comment by antonvash** [comment]
redis1 -192.168.96.2, redis2 -192.168.96.3 etc
![image](https://user-images.githubusercontent.com/25710668/93993580-fa593880-fd9f-11ea-9dbf-18b3fe328b9f.png)

**Comment by antonvash** [comment]
> redis1 -192.168.96.2, redis2 -192.168.96.3 etc
> ![image](https://user-images.githubusercontent.com/25710668/93993580-fa593880-fd9f-11ea-9dbf-18b3fe328b9f.png)

имейджы локально уже есть

**Comment by antonvash** [comment]
необходимо сентинеля 3 экземпляра

**Comment by antonvash** [comment]
либо раскоментить в docker-compose.yml 38 строку с REDIS_SENTINEL_QUORUM

**Comment by antonvash** [comment]
почему то на линуксовых композах не работает
```bash
    deploy:
      replicas: 3
```

**Comment by antonvash** [comment]
в 1.27 работает 
![image](https://user-images.githubusercontent.com/25710668/94000422-32fd1000-fda8-11ea-92ad-6fc772fd690f.png)

**Comment by antonvash** [comment]
пофиксил. вынес скэйл из композ файла в мэйкфайл
