### ISSUE TITLE
Ноды сохраняют свое состояние в статусе мастер в момент падения и после этого поднимаются

### ISSUE THREAD

**Issue by khodyrevyurii** [antonvash/redis-cluster#3]
Ноды сохраняют свое состояние в статусе мастер в момент падения и после этого поднимаются в этом состоянии:

Шаги по воспроизведению:
1. Выключаем redis1 (master)
2. Дожидаемся переключения мастер статуса на другую ноду
3. Выключаем redis2/redis3 в зависимости от того кто стал мастером
4. Дожидаемся переключения мастер статуса на последнюю ноду
5. Стартуем все контейнеры

Наблюдаем ситуацию:
![изображение](https://user-images.githubusercontent.com/52669813/94244911-fad60880-ff32-11ea-86d1-bb9697ee52f2.png)

После очередного дискавери со стороны Sentinel кластера, статус выправляется, но в этот момент пока ситуация существует (~20сек) происходит рассинхронизация Redis кластера, так как все 3 ноды считают себя мастером.
Как в таких случаях будет осуществляться отказоустойчивость?

**Comment by antonvash** [comment]
добавил метод балансировки по сырцу. в таком случае реквесты будут приходить на последнюю ноду. 
проверял 
```bash
for i in {1..200}; do echo -e "SET k$i v$i\r\nQUIT\r\n" | nc localhost 6379; done
```
консистентность есть
и добавил бэк для ридонли. чтоб балансировать геты
